version: '3'

services:
  app:
    image:
      ${DOCKERHUB_USERNAME}/django-products
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: unless-stopped

