apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-project-ingress
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: products.application.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: devops-project-service
              port:
                number: 80